info:
    app:
        name: JBeatnik
        description: ${info.app.name} is a Spring-Boot + AngularJS application
        version: 0.0.1

server:
    port: 9000

management:
    port: 9000
    address: 127.0.0.1
    contextPath: /manage
    security:
        enabled: true

authentication:
    oauth:
        clientid: jbeatnikapp
        secret: myOAuthSecret
        tokenValidityInSeconds: 1800 # Token is valid 30 minutes

    messageSource:
        cacheSeconds: 1