info:
    app:
        name: JBeatnik
        description: ${info.app.name} is a Spring-Boot + AngularJS application
        version: 0.0.1

server:
    port: 9000

management:
    port: 9000
    address: 127.0.0.1
    contextPath: /manage
    security:
        enabled: true

spring:
    thymeleaf:
        mode: HTML5
        cache: false

    datasource:
        url: jdbc:h2:mem:jbeatnik
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        username:
        password:
        schema: classpath:/sql/schema.sql
        data: classpath:/sql/data.sql

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none

authentication:
    oauth:
        clientid: jbeatnikapp
        secret: myOAuthSecret
        tokenValidityInSeconds: 1800 # Token is valid 30 minutes
