server:
  port: 9000

management:
  port: 9001
  address: 127.0.0.1
  contextPath: /admin

spring:
    thymeleaf:
        mode: HTML5
        cache: false

    datasource:
        url: jdbc:h2:mem:jbeatnik;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        driverClassName: org.h2.Driver
        username:
        password:

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show_sql: true