server:
    port: 9000

management:
    port: 9000
    address: 127.0.0.1
    contextPath: /manage
    security:
        role: ADMIN

endpoints:
    autoconfig:
        sensitive: true
    beans:
        sensitive: true
    configprops:
        sensitive: true
    dump:
        sensitive: true
    env:
        sensitive: true
    health:
        sensitive: false
    info:
        sensitive: true
    metrics:
        sensitive: true
    shutdown:
        sensitive: true
    trace:
        sensitive: true

spring:
    thymeleaf:
        mode: HTML5
        cache: false

    datasource:
        url: jdbc:h2:mem:jbeatnik
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        username:
        password:
        schema: classpath:/sql/schema.sql
        data: classpath:/sql/data.sql

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none

authentication:
    oauth:
        clientid: jbeatnikapp
        secret: myOAuthSecret
        tokenValidityInSeconds: 1800 # Token is valid 30 minutes
