server:
  port: 9000

management:
  port: 9001
  address: 127.0.0.1
  contextPath: /admin

spring:
    thymeleaf:
        mode: HTML5
        cache: false

    datasource:
        url: jdbc:hsqldb:mem:jbeatnik
        driverClassName: org.hsqldb.jdbcDriver
        username: sa
        password: